version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - run: mix deps.get
      - run: mix test